### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by faf-xff** [al0ne/suricata_optimize#1]
大佬，我们使用默认配置时出口数据很小，suricata丢包率（2%）也很小。但是增大内存和设置CPU亲和度后，这个出口数据很快就上来了,suricata丢包率也差不多。这个是和配置有关吗？不太懂为什么出口数据（最后输出数据）小了，suricata丢包率也小。不应该是大吗。

**Comment by al0ne** [comment]
留下你微信 我加你吧

**Comment by faf-xff** [comment]
> 留下你微信 我加你吧

15801311088
